require "../../../../editor-util-projects/canvas-2/smaug/visual-primitives/lib/basic_values.rb"
require "../../../../editor-util-projects/canvas-2/smaug/visual-primitives/lib/common_attributes.rb"
require "../../../../editor-util-projects/canvas-2/smaug/visual-primitives/lib/label.rb"
require "../../../../editor-util-projects/canvas-2/smaug/visual-primitives/lib/solid.rb"
require "../../../../editor-util-projects/canvas-2/smaug/visual-primitives/lib/sprite.rb"
require "../../../../editor-util-projects/canvas-2/smaug/visual-primitives/lib/border.rb"
require "../../../../editor-util-projects/canvas-2/smaug/visual-primitives/lib/line.rb"
require "../../../../editor-util-projects/canvas-2/smaug/visual-primitives/lib/volatile.rb"
require 'app/map.rb'
require 'app/bootstrap/tick.rb'
